# Generated by Django 4.1.1 on 2022-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.PositiveIntegerField()),
                ('operator_code', models.PositiveIntegerField()),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timer', models.DateTimeField()),
                ('text', models.CharField(max_length=255)),
                ('timer_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sending_time', models.DateTimeField()),
                ('sending_status', models.BooleanField(default=False)),
                ('distribution_id', models.BigIntegerField()),
                ('customer_id', models.BigIntegerField()),
            ],
        ),
    ]
