# Generated by Django 4.1.1 on 2022-09-14 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sending_status',
            new_name='sended_status',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11,11}$')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.customer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='distribution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.distribution'),
        ),
    ]
