# Generated by Django 4.1.1 on 2022-09-15 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_customer_tag_distribution_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='operator_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^7?1?\\d{10,10}$')]),
        ),
    ]
