# Generated by Django 4.1.1 on 2022-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0004_remove_customer_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
