# Generated by Django 4.1.1 on 2022-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_alter_distribution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='operator_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
