# Generated by Django 4.1.1 on 2022-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0008_alter_customer_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='operator_code',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
