# Generated by Django 4.1.1 on 2022-09-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0010_alter_customer_operator_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='timezone',
        ),
    ]
