# Generated by Django 4.1.1 on 2022-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0012_customer_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='filter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
