# Generated by Django 4.1.1 on 2022-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0014_alter_message_sended_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='timezone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sended_status',
            field=models.CharField(default='Waiting', max_length=255),
        ),
    ]
