# Generated by Django 4.1.1 on 2022-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0015_alter_customer_timezone_alter_message_sended_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='text',
            field=models.TextField(),
        ),
    ]
